#!/usr/bin/env bash
# install-auto-sync.sh — Install a macOS LaunchAgent that automatically syncs
# your local Claude settings to all configured VMs whenever they change.
#
# Uses launchd's WatchPaths to fire on changes to:
#   ~/.claude/settings.json   (permissions, plugins, MCPs, theme, effortLevel)
#   ~/.claude/CLAUDE.md       (global memory / instructions)
#   ~/.claude/skills/         (custom skills)
#   ~/.claude/commands/       (custom slash commands)
#
# The sync runs at most once every 5 seconds (throttled by launchd) so rapid
# back-to-back saves don't flood the VMs with rsync connections.
#
# Usage:
#   ./scripts/macos/install-auto-sync.sh          # install
#   ./scripts/macos/install-auto-sync.sh --remove # uninstall
#   ./scripts/macos/install-auto-sync.sh --status # show agent status
#   ./scripts/macos/install-auto-sync.sh --run    # run sync once right now

set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
info()    { echo -e "${CYAN}[auto-sync]${RESET} $*"; }
success() { echo -e "${GREEN}[auto-sync]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[auto-sync]${RESET} $*"; }
die()     { echo -e "${RED}[auto-sync] ERROR:${RESET} $*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
AGENT_LABEL="ai.jortelligence.claude-settings-sync"
PLIST_PATH="$HOME/Library/LaunchAgents/${AGENT_LABEL}.plist"
SYNC_SCRIPT="$REPO_ROOT/scripts/macos/run-claude-sync.sh"
LOG_FILE="/tmp/claude-settings-sync.log"
MODE="install"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remove) MODE="remove"; shift ;;
        --status) MODE="status"; shift ;;
        --run)    MODE="run";    shift ;;
        --help|-h) grep '^#' "$0" | head -20 | sed 's/^# \?//'; exit 0 ;;
        *) die "Unknown flag: $1" ;;
    esac
done

# ── STATUS ────────────────────────────────────────────────────────────────────
if [[ "$MODE" == "status" ]]; then
    if launchctl list "$AGENT_LABEL" &>/dev/null; then
        success "Auto-sync agent is running."
        launchctl list "$AGENT_LABEL"
    else
        warn "Auto-sync agent is NOT running."
        [[ -f "$PLIST_PATH" ]] && echo "  plist exists at $PLIST_PATH but agent is not loaded." || echo "  Run install-auto-sync.sh to install."
    fi
    echo ""
    echo "  Last sync log:"
    tail -20 "$LOG_FILE" 2>/dev/null || echo "  (no log yet)"
    exit 0
fi

# ── REMOVE ────────────────────────────────────────────────────────────────────
if [[ "$MODE" == "remove" ]]; then
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    rm -f "$PLIST_PATH"
    success "Auto-sync agent removed."
    exit 0
fi

# ── RUN ONCE ──────────────────────────────────────────────────────────────────
if [[ "$MODE" == "run" ]]; then
    exec bash "$SYNC_SCRIPT"
fi

# ── INSTALL ───────────────────────────────────────────────────────────────────
[[ "$(uname)" == "Darwin" ]] || die "This script is macOS-only. For Linux use a systemd path unit instead."

# Generate the sync runner script that will be called by launchd.
# It reads all configured VMs from their state files and syncs to each.
cat > "$SYNC_SCRIPT" << SCRIPT
#!/usr/bin/env bash
# Auto-generated by install-auto-sync.sh — re-run to regenerate.
set -euo pipefail

REPO_ROOT="${REPO_ROOT}"
LOG="${LOG_FILE}"
SYNC="\$REPO_ROOT/scripts/sync-claude-settings.sh"
TIMESTAMP="\$(date '+%Y-%m-%d %H:%M:%S')"

echo "" >> "\$LOG"
echo "[\$TIMESTAMP] Claude settings changed — syncing to VMs..." >> "\$LOG"

sync_vm() {
    local label="\$1" user="\$2" host="\$3" key="\$4"
    if [[ -n "\$host" ]]; then
        echo "  → \$label (\$host)" >> "\$LOG"
        bash "\$SYNC" "\$user" "\$host" "\$key" >> "\$LOG" 2>&1 && \
            echo "    ✓ done" >> "\$LOG" || \
            echo "    ✗ failed (VM may be off)" >> "\$LOG"
    fi
}

# GCE VM
GCE_STATE="${REPO_ROOT}/scripts/gce/.state/claude-discord-vm.env"
if [[ -f "\$GCE_STATE" ]]; then
    source "\$GCE_STATE"
    SSH_KEY_PATH="${HOME}/.ssh/id_ed25519"
    [[ ! -f "\$SSH_KEY_PATH" ]] && SSH_KEY_PATH="${HOME}/.ssh/id_rsa"
    sync_vm "GCE" "\${SSH_USER:-ubuntu}" "\${GCE_PUBLIC_IP:-}" "\$SSH_KEY_PATH"
fi

# Oracle Cloud VM
OCI_STATE="${REPO_ROOT}/scripts/oracle/.state/claude-discord-vm.env"
if [[ -f "\$OCI_STATE" ]]; then
    source "\$OCI_STATE"
    SSH_KEY_PATH="${HOME}/.ssh/id_ed25519"
    [[ ! -f "\$SSH_KEY_PATH" ]] && SSH_KEY_PATH="${HOME}/.ssh/id_rsa"
    sync_vm "Oracle" "\${SSH_USER:-ubuntu}" "\${OCI_PUBLIC_IP:-}" "\$SSH_KEY_PATH"
fi

echo "[\$TIMESTAMP] Sync complete." >> "\$LOG"
SCRIPT
chmod +x "$SYNC_SCRIPT"
info "Sync runner written to $SYNC_SCRIPT"

# Generate the launchd plist.
# WatchPaths fires whenever any of the listed paths are created, modified, or deleted.
# ThrottleInterval prevents bursts of saves from triggering many consecutive syncs.
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${AGENT_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${SYNC_SCRIPT}</string>
    </array>

    <!-- Fire whenever these files/directories change -->
    <key>WatchPaths</key>
    <array>
        <string>${HOME}/.claude/settings.json</string>
        <string>${HOME}/.claude/CLAUDE.md</string>
        <string>${HOME}/.claude/skills</string>
        <string>${HOME}/.claude/commands</string>
        <string>${HOME}/.claude/plugins/installed_plugins.json</string>
    </array>

    <!-- Don't fire more than once every 5 seconds during rapid saves -->
    <key>ThrottleInterval</key>
    <integer>5</integer>

    <key>StandardOutPath</key>
    <string>${LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_FILE}</string>

    <!-- Start at login -->
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

# Load the agent
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo ""
success "Auto-sync agent installed and running."
echo ""
echo "  Watching: ~/.claude/settings.json, CLAUDE.md, skills/, commands/"
echo "  On change → syncs to all VMs listed in scripts/gce/.state/ and scripts/oracle/.state/"
echo "  Log file: $LOG_FILE"
echo ""
echo "  Useful commands:"
echo "    Status:      ./scripts/macos/install-auto-sync.sh --status"
echo "    Run now:     ./scripts/macos/install-auto-sync.sh --run"
echo "    Uninstall:   ./scripts/macos/install-auto-sync.sh --remove"
echo ""
echo "  To add a new MCP server or skill:"
echo "    1. Install it locally as normal"
echo "    2. Auto-sync fires within 5 seconds and pushes to all VMs"
echo ""
