#!/usr/bin/env bash
# Auto-generated by install-auto-sync.sh — re-run to regenerate.
set -euo pipefail

REPO_ROOT="/Users/shujiang/Documents/claude-proxy"
LOG="/tmp/claude-settings-sync.log"
SYNC="$REPO_ROOT/scripts/sync-claude-settings.sh"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"

echo "" >> "$LOG"
echo "[$TIMESTAMP] Claude settings changed — syncing to VMs..." >> "$LOG"

sync_vm() {
    local label="$1" user="$2" host="$3" key="$4"
    if [[ -n "$host" ]]; then
        echo "  → $label ($host)" >> "$LOG"
        bash "$SYNC" "$user" "$host" "$key" >> "$LOG" 2>&1 &&             echo "    ✓ done" >> "$LOG" ||             echo "    ✗ failed (VM may be off)" >> "$LOG"
    fi
}

# GCE VM
GCE_STATE="/Users/shujiang/Documents/claude-proxy/scripts/gce/.state/claude-discord-vm.env"
if [[ -f "$GCE_STATE" ]]; then
    source "$GCE_STATE"
    SSH_KEY_PATH="/Users/shujiang/.ssh/id_ed25519"
    [[ ! -f "$SSH_KEY_PATH" ]] && SSH_KEY_PATH="/Users/shujiang/.ssh/id_rsa"
    sync_vm "GCE" "${SSH_USER:-ubuntu}" "${GCE_PUBLIC_IP:-}" "$SSH_KEY_PATH"
fi

# Oracle Cloud VM
OCI_STATE="/Users/shujiang/Documents/claude-proxy/scripts/oracle/.state/claude-discord-vm.env"
if [[ -f "$OCI_STATE" ]]; then
    source "$OCI_STATE"
    SSH_KEY_PATH="/Users/shujiang/.ssh/id_ed25519"
    [[ ! -f "$SSH_KEY_PATH" ]] && SSH_KEY_PATH="/Users/shujiang/.ssh/id_rsa"
    sync_vm "Oracle" "${SSH_USER:-ubuntu}" "${OCI_PUBLIC_IP:-}" "$SSH_KEY_PATH"
fi

echo "[$TIMESTAMP] Sync complete." >> "$LOG"
