#!/usr/bin/env bash
# provision-vm.sh — Create an OCI compute instance for Discord Claude sessions.
#
# ── Shape comparison (Always Free) ───────────────────────────────────────────
#
#   AMD  VM.Standard.E2.1.Micro   2 instances  1/8 OCPU  1 GB RAM each
#   ARM  VM.Standard.A1.Flex      1 instance   4 OCPUs   24 GB RAM total
#
#   For this project: ARM is the clear winner.
#   - AMD has 1 GB RAM per instance. After OS (~350 MB) and Docker daemon
#     (~100 MB), only ~550 MB remains. A single claude-discord container
#     idles at 150-250 MB — leaving almost no headroom and risking OOM under
#     any load. Running 2+ sessions on AMD is not viable.
#   - ARM has 24 GB RAM across 4 OCPUs. Easily supports 8-10 concurrent
#     Discord sessions. Docker build cache is fast. No OOM risk.
#
#   Default is ARM. Pass --shape amd if you want to test the AMD instance
#   (only worth it for a single very-light session or evaluation purposes).
#
# ── One-time prerequisites ───────────────────────────────────────────────────
#   1. Install OCI CLI:  https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm
#   2. Configure it:     oci setup config
#   3. Have an SSH key:  ssh-keygen -t ed25519 -C "oracle-claude"
#
# ── Usage ─────────────────────────────────────────────────────────────────────
#   ./scripts/oracle/provision-vm.sh                         # create ARM VM
#   ./scripts/oracle/provision-vm.sh --shape amd             # create AMD VM
#   ./scripts/oracle/provision-vm.sh --connect               # SSH into VM
#   ./scripts/oracle/provision-vm.sh --status                # show VM state
#   ./scripts/oracle/provision-vm.sh --delete                # destroy everything
#
#   ./scripts/oracle/provision-vm.sh --name my-vm --region ap-sydney-1

set -euo pipefail

BOLD='\033[1m'; CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
info()    { echo -e "${CYAN}[oracle]${RESET} $*"; }
success() { echo -e "${GREEN}[oracle]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[oracle]${RESET} $*"; }
die()     { echo -e "${RED}[oracle] ERROR:${RESET} $*" >&2; exit 1; }

# ── Defaults ──────────────────────────────────────────────────────────────────
SHAPE="arm"                       # arm (recommended) | amd
VM_NAME="claude-discord-vm"
OCI_REGION="${OCI_REGION:-}"      # auto-read from ~/.oci/config if empty
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519.pub}"
[[ ! -f "$SSH_KEY" ]] && SSH_KEY="$HOME/.ssh/id_rsa.pub"
BOOT_VOLUME_GB=50                 # fits within the 200 GB always-free allocation
MODE="create"                     # create | connect | delete | status

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_DIR="$SCRIPT_DIR/.state"
DEV_VARS="$REPO_ROOT/.dev.vars"

mkdir -p "$STATE_DIR"

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --shape)    SHAPE="$2";      shift 2 ;;
        --name)     VM_NAME="$2";    shift 2 ;;
        --region)   OCI_REGION="$2"; shift 2 ;;
        --ssh-key)  SSH_KEY="$2";    shift 2 ;;
        --connect)  MODE="connect";  shift   ;;
        --delete)   MODE="delete";   shift   ;;
        --status)   MODE="status";   shift   ;;
        --help|-h)  grep '^#' "$0" | head -40 | sed 's/^# \?//'; exit 0 ;;
        *) die "Unknown flag: $1. Run with --help." ;;
    esac
done

STATE_FILE="$STATE_DIR/${VM_NAME}.env"

# ── Prerequisite checks ───────────────────────────────────────────────────────
command -v oci  &>/dev/null || die "OCI CLI not installed. See https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm"
command -v jq   &>/dev/null || die "jq is required. Install: brew install jq"
command -v ssh  &>/dev/null || die "ssh is required."
command -v rsync &>/dev/null || die "rsync is required."
[[ -f "$HOME/.oci/config" ]]   || die "OCI CLI not configured. Run: oci setup config"
[[ -f "$SSH_KEY" ]]            || die "SSH public key not found: $SSH_KEY  (run: ssh-keygen -t ed25519)"

# ── Read OCI tenancy + region from ~/.oci/config ─────────────────────────────
TENANCY_ID=$(grep '^tenancy=' "$HOME/.oci/config" | head -1 | cut -d= -f2 | tr -d ' ')
[[ -z "$TENANCY_ID" ]] && die "Could not read tenancy from ~/.oci/config"

if [[ -z "$OCI_REGION" ]]; then
    OCI_REGION=$(grep '^region=' "$HOME/.oci/config" | head -1 | cut -d= -f2 | tr -d ' ')
fi
[[ -z "$OCI_REGION" ]] && die "OCI region not set. Add --region or set it in ~/.oci/config"

# Convenience SSH alias — used everywhere below
SSH_USER="ubuntu"   # Canonical Ubuntu images use 'ubuntu'
OCI_FLAGS="--region $OCI_REGION"

# ── State helpers ─────────────────────────────────────────────────────────────
state_write() {
    cat > "$STATE_FILE" << EOF
# Auto-generated by provision-vm.sh — do not edit manually.
OCI_INSTANCE_ID="$1"
OCI_VCN_ID="$2"
OCI_SUBNET_ID="$3"
OCI_PUBLIC_IP="$4"
OCI_SHAPE="$5"
OCI_REGION="$OCI_REGION"
SSH_USER="$SSH_USER"
VM_NAME="$VM_NAME"
EOF
    chmod 600 "$STATE_FILE"
}

state_load() {
    [[ -f "$STATE_FILE" ]] || die "No state found for '$VM_NAME'. Run provision-vm.sh to create it."
    # shellcheck source=/dev/null
    source "$STATE_FILE"
}

ssh_cmd() {
    local ip="$1"; shift
    ssh -i "${SSH_KEY%.pub}" \
        -o StrictHostKeyChecking=no \
        -o ConnectTimeout=10 \
        -o BatchMode=yes \
        "$SSH_USER@$ip" "$@"
}

wait_for_ssh() {
    local ip="$1"
    info "Waiting for SSH on $ip..."
    for i in $(seq 1 60); do
        if ssh_cmd "$ip" "echo ok" &>/dev/null; then
            echo ""
            success "SSH ready."
            return
        fi
        printf "."
        sleep 5
    done
    echo ""
    die "SSH did not become available within 5 minutes."
}

# ── STATUS ────────────────────────────────────────────────────────────────────
if [[ "$MODE" == "status" ]]; then
    state_load
    echo ""
    echo -e "${BOLD}  Oracle VM: $VM_NAME${RESET}"
    echo "  Shape    : $OCI_SHAPE"
    echo "  Region   : $OCI_REGION"
    echo "  Public IP: $OCI_PUBLIC_IP"
    echo ""
    LIFECYCLE=$(oci compute instance get --instance-id "$OCI_INSTANCE_ID" $OCI_FLAGS \
        2>/dev/null | jq -r '.data."lifecycle-state"' || echo "unknown")
    echo "  State    : $LIFECYCLE"
    echo ""
    if [[ "$LIFECYCLE" == "RUNNING" ]]; then
        echo "  Running sessions:"
        ssh_cmd "$OCI_PUBLIC_IP" \
            "docker ps --filter name=discord-session- --format '    {{.Names}}  {{.Status}}'" 2>/dev/null || \
            echo "    (could not reach Docker)"
    fi
    echo ""
    exit 0
fi

# ── CONNECT ───────────────────────────────────────────────────────────────────
if [[ "$MODE" == "connect" ]]; then
    state_load
    info "Connecting to $VM_NAME ($OCI_PUBLIC_IP)..."
    exec ssh -i "${SSH_KEY%.pub}" \
        -o StrictHostKeyChecking=no \
        "$SSH_USER@$OCI_PUBLIC_IP"
fi

# ── DELETE ────────────────────────────────────────────────────────────────────
if [[ "$MODE" == "delete" ]]; then
    state_load
    echo ""
    warn "This will permanently delete VM '$VM_NAME' and its associated VCN/subnet."
    warn "All running Docker containers and their volumes will be destroyed."
    echo ""
    read -rp "  Type the VM name to confirm: " confirm
    [[ "$confirm" != "$VM_NAME" ]] && { echo "  Aborted."; exit 1; }

    info "Terminating instance $OCI_INSTANCE_ID..."
    oci compute instance terminate \
        --instance-id "$OCI_INSTANCE_ID" \
        --preserve-boot-volume false \
        --force \
        $OCI_FLAGS

    info "Waiting for instance to terminate..."
    for i in $(seq 1 60); do
        STATE=$(oci compute instance get --instance-id "$OCI_INSTANCE_ID" $OCI_FLAGS \
            2>/dev/null | jq -r '.data."lifecycle-state"' || echo "TERMINATED")
        [[ "$STATE" == "TERMINATED" ]] && break
        printf "."
        sleep 5
    done
    echo ""

    info "Deleting subnet $OCI_SUBNET_ID..."
    oci network subnet delete --subnet-id "$OCI_SUBNET_ID" --force $OCI_FLAGS 2>/dev/null || true

    info "Deleting VCN $OCI_VCN_ID..."
    # Must delete IGW + security list + route table first — OCI handles this via vcn delete cascade
    oci network vcn delete --vcn-id "$OCI_VCN_ID" --force $OCI_FLAGS 2>/dev/null || true

    rm -f "$STATE_FILE"
    success "VM '$VM_NAME' and network resources deleted."
    exit 0
fi

# ── CREATE ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  Oracle Cloud — Provisioning Discord Bot VM${RESET}"
echo "  Shape    : $([ "$SHAPE" = arm ] && echo 'VM.Standard.A1.Flex (4 OCPU, 24 GB RAM)' || echo 'VM.Standard.E2.1.Micro (1/8 OCPU, 1 GB RAM)')"
echo "  Name     : $VM_NAME"
echo "  Region   : $OCI_REGION"
echo "  SSH key  : $SSH_KEY"
echo ""

if [[ "$SHAPE" == "amd" ]]; then
    warn "AMD (E2.1.Micro) has only 1 GB RAM. After OS + Docker overhead, only"
    warn "~550 MB is available. This limits you to 1 session and risks OOM."
    warn "ARM is strongly recommended for this workload."
    echo ""
fi

# ── Step 1: Pick availability domain ─────────────────────────────────────────
info "Fetching availability domains..."
AD_NAME=$(oci iam availability-domain list \
    --compartment-id "$TENANCY_ID" \
    $OCI_FLAGS \
    | jq -r '.data[0].name')
[[ -z "$AD_NAME" ]] && die "Could not get availability domain."
info "Using AD: $AD_NAME"

# ── Step 2: Find Ubuntu 22.04 image for chosen shape ────────────────────────
if [[ "$SHAPE" == "arm" ]]; then
    OCI_SHAPE="VM.Standard.A1.Flex"
    SHAPE_FILTER="VM.Standard.A1.Flex"
else
    OCI_SHAPE="VM.Standard.E2.1.Micro"
    SHAPE_FILTER="VM.Standard.E2.1.Micro"
fi

info "Finding latest Canonical Ubuntu 22.04 image for $OCI_SHAPE..."
IMAGE_ID=$(oci compute image list \
    --compartment-id "$TENANCY_ID" \
    --operating-system "Canonical Ubuntu" \
    --operating-system-version "22.04" \
    --shape "$SHAPE_FILTER" \
    --sort-by TIMECREATED \
    --sort-order DESC \
    --limit 1 \
    $OCI_FLAGS \
    | jq -r '.data[0].id')
[[ -z "$IMAGE_ID" || "$IMAGE_ID" == "null" ]] && \
    die "Could not find Ubuntu 22.04 image for $OCI_SHAPE in $OCI_REGION."
info "Image: $IMAGE_ID"

# ── Step 3: Create VCN ────────────────────────────────────────────────────────
info "Creating VCN..."
VCN_ID=$(oci network vcn create \
    --compartment-id "$TENANCY_ID" \
    --cidr-block "10.0.0.0/16" \
    --display-name "${VM_NAME}-vcn" \
    --wait-for-state AVAILABLE \
    $OCI_FLAGS \
    | jq -r '.data.id')
[[ -z "$VCN_ID" ]] && die "Failed to create VCN."
info "VCN: $VCN_ID"

# ── Step 4: Create Internet Gateway ──────────────────────────────────────────
info "Creating Internet Gateway..."
IGW_ID=$(oci network internet-gateway create \
    --compartment-id "$TENANCY_ID" \
    --vcn-id "$VCN_ID" \
    --is-enabled true \
    --display-name "${VM_NAME}-igw" \
    --wait-for-state AVAILABLE \
    $OCI_FLAGS \
    | jq -r '.data.id')

# ── Step 5: Add default route (0.0.0.0/0 → IGW) ──────────────────────────────
info "Configuring default route..."
DEFAULT_RT_ID=$(oci network vcn get --vcn-id "$VCN_ID" $OCI_FLAGS \
    | jq -r '.data."default-route-table-id"')
oci network route-table update \
    --rt-id "$DEFAULT_RT_ID" \
    --route-rules "[{\"cidrBlock\":\"0.0.0.0/0\",\"networkEntityId\":\"$IGW_ID\"}]" \
    --force \
    $OCI_FLAGS > /dev/null

# ── Step 6: Configure default security list ───────────────────────────────────
# Allow: SSH inbound from anywhere, all egress.
# No inbound HTTP/HTTPS needed — bot connects OUT to Discord; Claude connects OUT to proxy.
info "Configuring security rules (SSH in + all egress)..."
DEFAULT_SL_ID=$(oci network vcn get --vcn-id "$VCN_ID" $OCI_FLAGS \
    | jq -r '.data."default-security-list-id"')
oci network security-list update \
    --security-list-id "$DEFAULT_SL_ID" \
    --ingress-security-rules '[
        {
            "source": "0.0.0.0/0",
            "protocol": "6",
            "isStateless": false,
            "tcpOptions": {
                "destinationPortRange": {"min": 22, "max": 22}
            }
        }
    ]' \
    --egress-security-rules '[
        {
            "destination": "0.0.0.0/0",
            "protocol": "all",
            "isStateless": false
        }
    ]' \
    --force \
    $OCI_FLAGS > /dev/null

# ── Step 7: Create public subnet ──────────────────────────────────────────────
info "Creating public subnet..."
SUBNET_ID=$(oci network subnet create \
    --compartment-id "$TENANCY_ID" \
    --vcn-id "$VCN_ID" \
    --cidr-block "10.0.0.0/24" \
    --display-name "${VM_NAME}-subnet" \
    --route-table-id "$DEFAULT_RT_ID" \
    --security-list-ids "[\"$DEFAULT_SL_ID\"]" \
    --prohibit-public-ip-on-vnic false \
    --wait-for-state AVAILABLE \
    $OCI_FLAGS \
    | jq -r '.data.id')
[[ -z "$SUBNET_ID" ]] && die "Failed to create subnet."

# ── Step 8: Launch instance ───────────────────────────────────────────────────
info "Launching instance ($OCI_SHAPE)..."

if [[ "$SHAPE" == "arm" ]]; then
    SHAPE_CONFIG='{"ocpus":4,"memoryInGBs":24}'
else
    SHAPE_CONFIG='{"ocpus":0.125,"memoryInGBs":1}'
fi

SSH_PUB_KEY=$(cat "$SSH_KEY")
INSTANCE_ID=$(oci compute instance launch \
    --compartment-id "$TENANCY_ID" \
    --availability-domain "$AD_NAME" \
    --shape "$OCI_SHAPE" \
    --shape-config "$SHAPE_CONFIG" \
    --source-details "{\"sourceType\":\"image\",\"imageId\":\"$IMAGE_ID\",\"bootVolumeSizeInGBs\":$BOOT_VOLUME_GB}" \
    --create-vnic-details "{\"subnetId\":\"$SUBNET_ID\",\"assignPublicIp\":true,\"displayName\":\"${VM_NAME}-vnic\"}" \
    --metadata "{\"ssh_authorized_keys\":\"$SSH_PUB_KEY\"}" \
    --display-name "$VM_NAME" \
    $OCI_FLAGS \
    | jq -r '.data.id')
[[ -z "$INSTANCE_ID" ]] && die "Failed to launch instance."
info "Instance launched: $INSTANCE_ID"

# ── Step 9: Wait for RUNNING ──────────────────────────────────────────────────
info "Waiting for instance to reach RUNNING state..."
for i in $(seq 1 60); do
    LIFECYCLE=$(oci compute instance get --instance-id "$INSTANCE_ID" $OCI_FLAGS \
        | jq -r '.data."lifecycle-state"')
    [[ "$LIFECYCLE" == "RUNNING" ]] && break
    printf "."
    sleep 5
done
echo ""
[[ "$LIFECYCLE" != "RUNNING" ]] && die "Instance did not reach RUNNING state."

# ── Step 10: Get public IP ────────────────────────────────────────────────────
info "Fetching public IP..."
PUBLIC_IP=$(oci compute instance list-vnics \
    --instance-id "$INSTANCE_ID" \
    $OCI_FLAGS \
    | jq -r '.data[0]."public-ip"')
[[ -z "$PUBLIC_IP" || "$PUBLIC_IP" == "null" ]] && die "Could not get public IP."
success "Public IP: $PUBLIC_IP"

# ── Step 11: Save state ───────────────────────────────────────────────────────
state_write "$INSTANCE_ID" "$VCN_ID" "$SUBNET_ID" "$PUBLIC_IP" "$OCI_SHAPE"

# ── Step 12: Wait for SSH ─────────────────────────────────────────────────────
wait_for_ssh "$PUBLIC_IP"

# ── Step 13: Install Docker ───────────────────────────────────────────────────
info "Installing Docker on VM..."
ssh_cmd "$PUBLIC_IP" "bash -s" << 'DOCKER_INSTALL'
set -e
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends ca-certificates curl rsync
curl -fsSL https://get.docker.com | sudo sh
sudo usermod -aG docker ubuntu
# Enable Docker to start on boot
sudo systemctl enable docker
echo "[setup] Docker installed: $(docker --version 2>/dev/null || sudo docker --version)"
DOCKER_INSTALL

success "Docker installed."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  VM ready.${RESET}"
echo "  Name     : $VM_NAME"
echo "  Shape    : $OCI_SHAPE"
echo "  IP       : $PUBLIC_IP"
echo "  State    : $STATE_FILE"
echo ""
echo "  Next steps:"
echo "    Build and start a Discord session:"
echo "    ./scripts/oracle/deploy-session.sh build"
echo "    ./scripts/oracle/deploy-session.sh start --channel-id CHANNEL_ID --discord-users USER_ID"
echo ""
echo "  Reconnect:"
echo "    ./scripts/oracle/provision-vm.sh --connect"
echo ""
echo "  Stop a session:"
echo "    ./scripts/oracle/deploy-session.sh stop --channel-id CHANNEL_ID"
echo ""
echo "  Destroy everything:"
echo "    ./scripts/oracle/provision-vm.sh --delete"
echo ""
